# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  # Redirect default Netlify subdomain to primary domain
  from = https://nervous-golick-34c7f9.netlify.com/*
  to = https://dev.pineapplepad.com/:splat
  status = 301
  force = true

[[redirects]]
  from = http://nervous-golick-34c7f9.netlify.com/*
  to = http://dev.pineapplepad.com/:splat
  status = 301
  force = true