// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:c42f576b-a5c0-4100-8df4-f056c327fac4',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '37fcc8c161894ca487faaec1875b5dfc',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7d492984-a3fb-4637-ba5b-6ec20956904b',
    'aws_project_name': 'PineapplePad',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'pineapplepad-mobilehub-1705399922',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_hUcFp3lmI',
    'aws_user_pools_web_client_id': '3kt25am2o4ip4udbv5hpgcu380',
}

export default awsmobile;
