// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"fxz9g6o80j","name":"account_attributesCRUD","description":"","endpoint":"https://fxz9g6o80j.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/account_attributes","/account_attributes/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:c42f576b-a5c0-4100-8df4-f056c327fac4',
    'aws_cognito_region': 'us-east-1',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"pineapplepad-mobilehub-1705399922-account_attributes","attributes":[{"name":"userId","type":"S"},{"name":"apartments","type":"BOOL"},{"name":"bedrooms","type":"N"},{"name":"max_rent","type":"N"},{"name":"move_in_date","type":"S"},{"name":"neighborhood","type":"S"},{"name":"rent_house","type":"BOOL"},{"name":"source","type":"S"},{"name":"special_requests","type":"S"},{"name":"state","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId"}],
    'aws_mobile_analytics_app_id': '37fcc8c161894ca487faaec1875b5dfc',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7d492984-a3fb-4637-ba5b-6ec20956904b',
    'aws_project_name': 'PineapplePad',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'pineapplepad-deployments-mobilehub-1705399922',
    'aws_resource_name_prefix': 'pineapplepad-mobilehub-1705399922',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_hUcFp3lmI',
    'aws_user_pools_web_client_id': '3kt25am2o4ip4udbv5hpgcu380',
}

export default awsmobile;
