// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2e7688b7-d33f-4618-8620-26ce3f84310c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9mlIoPTfj",
    "aws_user_pools_web_client_id": "5ht3a96h0f35qbbu1h6th3npm9",
    "aws_cloud_logic_custom": [
        {
            "name": "accountattributes",
            "endpoint": "https://98qc584ed6.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
